# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{action_auditor}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Powell"]
  s.date = %q{2009-11-27}
  s.description = %q{Keep an audit trail of actions in your application}
  s.email = %q{fauxparse@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/action_auditor_migration/USAGE",
     "generators/action_auditor_migration/action_auditor_migration_generator.rb",
     "generators/action_auditor_migration/templates/migration.rb",
     "install.rb",
     "lib/action_auditor.rb",
     "lib/action_auditor/auditor/active_record.rb",
     "lib/action_auditor/auditor/base.rb",
     "lib/action_auditor/auditor/simple.rb",
     "lib/action_auditor/extensions/action_controller.rb",
     "rails/init.rb",
     "spec/action_auditor_spec.rb",
     "spec/controllers/controller_integration_spec.rb",
     "spec/spec_helper.rb",
     "tasks/rdoc.rake",
     "tasks/spec.rake",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/fauxparse/action_auditor}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Keep an audit trail of actions in your application}
  s.test_files = [
    "spec/action_auditor_spec.rb",
     "spec/controllers/controller_integration_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

